// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantApp.Data;

#nullable disable

namespace RestaurantApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240417200857_SeedReservationAndCapacity")]
    partial class SeedReservationAndCapacity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TownId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TownId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("553fb0ed-0384-4aeb-f80d-08dc21d76b67"),
                            PostalCode = "NB12 JAT",
                            Street = "Baker Street",
                            TownId = 1
                        });
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirsName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShoppingCartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ShoppingCartId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e15c76a2-31a0-4cc1-8bd9-9f7cd300f3c9"),
                            AccessFailedCount = 0,
                            AddressId = new Guid("553fb0ed-0384-4aeb-f80d-08dc21d76b67"),
                            ConcurrencyStamp = "74adc793-39e9-4d56-87de-0d61178a7f81",
                            Email = "john@gmail.com",
                            EmailConfirmed = true,
                            FirsName = "John",
                            LastName = "Walker",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN@GMAIL.COM",
                            NormalizedUserName = "JOHN",
                            PasswordHash = "AQAAAAEAACcQAAAAEMiv7Pj15k1hSQawyw6DRoHVaWCh/Y6xZPpEYElZxM0Y9IUbnZroTs9ehsI9kktQxw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9ecf1bc7-70c9-4b6c-8877-b227c416adbe",
                            ShoppingCartId = new Guid("eaeca7c9-c81f-4d4a-aed6-8eae37e1460f"),
                            TwoFactorEnabled = false,
                            UserName = "john"
                        },
                        new
                        {
                            Id = new Guid("e15c76a2-31a0-4cc1-8bd9-9f7cd380f3c9"),
                            AccessFailedCount = 0,
                            AddressId = new Guid("553fb0ed-0384-4aeb-f80d-08dc21d76b67"),
                            ConcurrencyStamp = "0729a89c-29a0-4135-bad0-aef3b8b29c89",
                            Email = "jack@gmail.com",
                            EmailConfirmed = true,
                            FirsName = "Jack",
                            LastName = "Jackson",
                            LockoutEnabled = false,
                            NormalizedEmail = "JACK@GMAIL.COM",
                            NormalizedUserName = "JACK",
                            PasswordHash = "AQAAAAEAACcQAAAAEOERtMW2EycJS+K4TPb7NrV5Empz9p+chdmg0KkZj1104I2FfWj8YtoyQTq6Ami6rA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fd31269b-5130-4bb1-94da-249b836b74ba",
                            ShoppingCartId = new Guid("b574b35d-9fcb-4403-aca3-0feb4479804b"),
                            TwoFactorEnabled = false,
                            UserName = "jack"
                        },
                        new
                        {
                            Id = new Guid("e15c57a2-31a0-4cc1-8bd9-9f7cd398f3c9"),
                            AccessFailedCount = 0,
                            AddressId = new Guid("553fb0ed-0384-4aeb-f80d-08dc21d76b67"),
                            ConcurrencyStamp = "d045c09b-f219-43d6-9574-cf4aa5598186",
                            Email = "paul@gmail.com",
                            EmailConfirmed = true,
                            FirsName = "Paul",
                            LastName = "Robinson",
                            LockoutEnabled = false,
                            NormalizedEmail = "PAUL@GMAIL.COM",
                            NormalizedUserName = "PAUL",
                            PasswordHash = "AQAAAAEAACcQAAAAELNEWlV0PlBoMcAveO4hlJVo7NVOlErGjLYeZF5+LqHMjTy8sQJAUKcMJglsJVRerg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fd6701c7-3950-4e79-8f11-25358591b913",
                            ShoppingCartId = new Guid("9e3cdb70-6f53-4a89-ae00-639f5e265219"),
                            TwoFactorEnabled = false,
                            UserName = "paul"
                        });
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.CapacitySlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CurrentCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("SlotDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CapacitySlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentCapacity = 94,
                            SlotDate = new DateTime(2024, 4, 27, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            TotalCapacity = 100
                        },
                        new
                        {
                            Id = 2,
                            CurrentCapacity = 94,
                            SlotDate = new DateTime(2024, 5, 7, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            TotalCapacity = 100
                        },
                        new
                        {
                            Id = 3,
                            CurrentCapacity = 94,
                            SlotDate = new DateTime(2024, 5, 17, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            TotalCapacity = 100
                        },
                        new
                        {
                            Id = 4,
                            CurrentCapacity = 94,
                            SlotDate = new DateTime(2024, 6, 1, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            TotalCapacity = 100
                        });
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.CartProduct", b =>
                {
                    b.Property<Guid>("ShoppingCartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartProducts");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Starters"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Salads"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Specialty"
                        });
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChatUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ChatUserId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EndEvent")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartEvent")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Christmas Day",
                            EndEvent = new DateTime(2024, 12, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StartEvent = new DateTime(2024, 12, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Christmas Day"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Heppy New Year",
                            EndEvent = new DateTime(2024, 12, 31, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StartEvent = new DateTime(2024, 12, 31, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Heppy New Year"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Easter Sunday",
                            EndEvent = new DateTime(2024, 3, 31, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StartEvent = new DateTime(2024, 3, 31, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Easter Sunday"
                        });
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.GalleryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caption")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedBy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePaht")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("GalleryImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 4, 17, 21, 8, 57, 243, DateTimeKind.Local).AddTicks(1024),
                            ImagePaht = "img/gallery/gallery-1.jpg",
                            LikesCount = 0,
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 4, 16, 21, 8, 57, 243, DateTimeKind.Local).AddTicks(1028),
                            ImagePaht = "img/gallery/gallery-2.jpg",
                            LikesCount = 0,
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 4, 15, 21, 8, 57, 243, DateTimeKind.Local).AddTicks(1031),
                            ImagePaht = "img/gallery/gallery-3.jpg",
                            LikesCount = 0,
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2024, 4, 14, 21, 8, 57, 243, DateTimeKind.Local).AddTicks(1033),
                            ImagePaht = "img/gallery/gallery-4.jpg",
                            LikesCount = 0,
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2024, 4, 13, 21, 8, 57, 243, DateTimeKind.Local).AddTicks(1035),
                            ImagePaht = "img/gallery/gallery-5.jpg",
                            LikesCount = 0,
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2024, 4, 12, 21, 8, 57, 243, DateTimeKind.Local).AddTicks(1036),
                            ImagePaht = "img/gallery/gallery-6.jpg",
                            LikesCount = 0,
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2024, 4, 11, 21, 8, 57, 243, DateTimeKind.Local).AddTicks(1038),
                            ImagePaht = "img/gallery/gallery-7.jpg",
                            LikesCount = 0,
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2024, 4, 10, 21, 8, 57, 243, DateTimeKind.Local).AddTicks(1040),
                            ImagePaht = "img/gallery/gallery-8.jpg",
                            LikesCount = 0,
                            ViewsCount = 0
                        });
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Description = "Lorem, deren, trataro, filede, nerada",
                            Image = "img/menu/lobster-bisque.jpg",
                            Name = "Lobster Bisque",
                            Price = 5.95m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Description = "Lorem, deren, trataro, filede, nerada",
                            Image = "img/menu/bread-barrel.jpg",
                            Name = "Bread Barrel",
                            Price = 6.95m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "A delicate crab cake served on a toasted roll with lettuce and tartar sauce\r\n",
                            Image = "img/menu/cake.jpg",
                            Name = "Crab Cake",
                            Price = 7.95m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Grilled chicken with provolone, artichoke hearts, and roasted red pesto\r\n",
                            Image = "img/menu/tuscan-grilled.jpg",
                            Name = "Tuscan Grilled",
                            Price = 9.95m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Lorem, deren, trataro, filede, nerada",
                            Image = "img/menu/mozzarella.jpg",
                            Name = "Mozzarella Stick",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Fresh spinach, crisp romaine, tomatoes, and Greek olives",
                            Image = "img/menu/greek-salad.jpg",
                            Name = "Greek Salad",
                            Price = 9.95m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Fresh spinach with mushrooms, hard boiled egg, and warm bacon vinaigrette",
                            Image = "img/menu/spinach-salad.jpg",
                            Name = "Spinach Salad",
                            Price = 9.95m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Plump lobster meat, mayo and crisp lettuce on a toasted bulky roll",
                            Image = "img/menu/lobster-roll.jpg",
                            Name = "Lobster Roll",
                            Price = 9.95m
                        });
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CapacitySlotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CapacitySlotId");

                    b.HasIndex("EventId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6460bdc-658d-4163-b725-44514e797078"),
                            ApplicationUserId = new Guid("e15c76a2-31a0-4cc1-8bd9-9f7cd300f3c9"),
                            CapacitySlotId = 1,
                            Date = new DateTime(2024, 4, 27, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@gmail.com",
                            FirstName = "John",
                            LastName = "Walker",
                            PeopleCount = 2,
                            PhoneNumber = "07708064509"
                        },
                        new
                        {
                            Id = new Guid("8ac38b36-3a93-4c92-add3-e1d8eaa0d1c4"),
                            ApplicationUserId = new Guid("e15c76a2-31a0-4cc1-8bd9-9f7cd380f3c9"),
                            CapacitySlotId = 1,
                            Date = new DateTime(2024, 4, 27, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            Email = "jack@gmail.com",
                            FirstName = "Jack",
                            LastName = "Jackson",
                            PeopleCount = 2,
                            PhoneNumber = "07708064509"
                        },
                        new
                        {
                            Id = new Guid("8d39fd7a-4435-465b-a078-ac0867c8d188"),
                            ApplicationUserId = new Guid("e15c57a2-31a0-4cc1-8bd9-9f7cd398f3c9"),
                            CapacitySlotId = 1,
                            Date = new DateTime(2024, 4, 27, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            Email = "paul@gmail.com",
                            FirstName = "Paul",
                            LastName = "Robinson",
                            PeopleCount = 2,
                            PhoneNumber = "07708064509"
                        },
                        new
                        {
                            Id = new Guid("c6e6ca2b-7207-4005-99b3-a1e03fb40d9a"),
                            ApplicationUserId = new Guid("e15c76a2-31a0-4cc1-8bd9-9f7cd300f3c9"),
                            CapacitySlotId = 2,
                            Date = new DateTime(2024, 5, 7, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@gmail.com",
                            FirstName = "John",
                            LastName = "Walker",
                            PeopleCount = 2,
                            PhoneNumber = "07708064509"
                        },
                        new
                        {
                            Id = new Guid("a491dfca-5207-4d87-93a5-32cdbc335ee9"),
                            ApplicationUserId = new Guid("e15c76a2-31a0-4cc1-8bd9-9f7cd380f3c9"),
                            CapacitySlotId = 2,
                            Date = new DateTime(2024, 5, 7, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            Email = "jack@gmail.com",
                            FirstName = "Jack",
                            LastName = "Jackson",
                            PeopleCount = 2,
                            PhoneNumber = "07708064509"
                        },
                        new
                        {
                            Id = new Guid("3f37879f-31b0-44c1-bfd0-0b8f735e1eec"),
                            ApplicationUserId = new Guid("e15c57a2-31a0-4cc1-8bd9-9f7cd398f3c9"),
                            CapacitySlotId = 2,
                            Date = new DateTime(2024, 5, 7, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            Email = "paul@gmail.com",
                            FirstName = "Paul",
                            LastName = "Robinson",
                            PeopleCount = 2,
                            PhoneNumber = "07708064509"
                        },
                        new
                        {
                            Id = new Guid("63b0b804-c892-4ba3-a26a-31f0905bd3a3"),
                            ApplicationUserId = new Guid("e15c76a2-31a0-4cc1-8bd9-9f7cd300f3c9"),
                            CapacitySlotId = 3,
                            Date = new DateTime(2024, 5, 17, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@gmail.com",
                            FirstName = "John",
                            LastName = "Walker",
                            PeopleCount = 2,
                            PhoneNumber = "07708064509"
                        },
                        new
                        {
                            Id = new Guid("ae553d8c-b03b-45d9-a910-aec5b031d665"),
                            ApplicationUserId = new Guid("e15c76a2-31a0-4cc1-8bd9-9f7cd380f3c9"),
                            CapacitySlotId = 3,
                            Date = new DateTime(2024, 5, 17, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            Email = "jack@gmail.com",
                            FirstName = "Jack",
                            LastName = "Jackson",
                            PeopleCount = 2,
                            PhoneNumber = "07708064509"
                        },
                        new
                        {
                            Id = new Guid("88340b80-4900-477f-b717-b9106c886171"),
                            ApplicationUserId = new Guid("e15c57a2-31a0-4cc1-8bd9-9f7cd398f3c9"),
                            CapacitySlotId = 3,
                            Date = new DateTime(2024, 5, 17, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            Email = "paul@gmail.com",
                            FirstName = "Paul",
                            LastName = "Robinson",
                            PeopleCount = 2,
                            PhoneNumber = "07708064509"
                        },
                        new
                        {
                            Id = new Guid("f4701ffc-2949-44dc-bd5c-ae96c9280c93"),
                            ApplicationUserId = new Guid("e15c76a2-31a0-4cc1-8bd9-9f7cd300f3c9"),
                            CapacitySlotId = 4,
                            Date = new DateTime(2024, 6, 1, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@gmail.com",
                            FirstName = "John",
                            LastName = "Walker",
                            PeopleCount = 2,
                            PhoneNumber = "07708064509"
                        },
                        new
                        {
                            Id = new Guid("59bcf48b-9e08-4d08-96ef-db6c85b8cba7"),
                            ApplicationUserId = new Guid("e15c76a2-31a0-4cc1-8bd9-9f7cd380f3c9"),
                            CapacitySlotId = 4,
                            Date = new DateTime(2024, 6, 1, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            Email = "jack@gmail.com",
                            FirstName = "Jack",
                            LastName = "Jackson",
                            PeopleCount = 2,
                            PhoneNumber = "07708064509"
                        },
                        new
                        {
                            Id = new Guid("f95c01b6-c43b-401e-9a1e-8bb34b25ac2b"),
                            ApplicationUserId = new Guid("e15c57a2-31a0-4cc1-8bd9-9f7cd398f3c9"),
                            CapacitySlotId = 4,
                            Date = new DateTime(2024, 6, 1, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            Email = "paul@gmail.com",
                            FirstName = "Paul",
                            LastName = "Robinson",
                            PeopleCount = 2,
                            PhoneNumber = "07708064509"
                        });
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eaeca7c9-c81f-4d4a-aed6-8eae37e1460f"),
                            Price = 0m
                        },
                        new
                        {
                            Id = new Guid("b574b35d-9fcb-4403-aca3-0feb4479804b"),
                            Price = 0m
                        },
                        new
                        {
                            Id = new Guid("9e3cdb70-6f53-4a89-ae00-639f5e265219"),
                            Price = 0m
                        });
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Town", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TownName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Towns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TownName = "London"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Address", b =>
                {
                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.Town", "Town")
                        .WithMany()
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Town");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.ShoppingCart", "ShoppingCart")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("RestaurantApp.Infrastructure.Data.Models.ApplicationUser", "ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.CartProduct", b =>
                {
                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("CartProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("CartProducts")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Chat", b =>
                {
                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.ApplicationUser", "ChatUser")
                        .WithMany()
                        .HasForeignKey("ChatUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChatUser");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.ChatMessage", b =>
                {
                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.Chat", "Chat")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.GalleryImage", b =>
                {
                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Order", b =>
                {
                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.OrderItem", b =>
                {
                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Product", b =>
                {
                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Reservation", b =>
                {
                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.CapacitySlot", "CapacitySlot")
                        .WithMany("Reservations")
                        .HasForeignKey("CapacitySlotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RestaurantApp.Infrastructure.Data.Models.Event", "Event")
                        .WithMany("Reservations")
                        .HasForeignKey("EventId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("CapacitySlot");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.CapacitySlot", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Chat", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Event", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.Product", b =>
                {
                    b.Navigation("CartProducts");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RestaurantApp.Infrastructure.Data.Models.ShoppingCart", b =>
                {
                    b.Navigation("ApplicationUser")
                        .IsRequired();

                    b.Navigation("CartProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
